In [1]:
import pandas as pd
import os

# get the parent directory
parent_dir = os.path.dirname(os.getcwd())

# replace \ with / for windows
parent_dir = parent_dir.replace('\\', '/')

dir = parent_dir + '/features/'

print(dir)

c:/Users/Stone/Downloads/iot_23/features/

In [2]:
# read all the files in the directory
files = os.listdir(dir)

# print the file names with their index and size
for i in range(len(files)):
    print(i, files[i], os.path.getsize(dir + files[i]))

0 Attack_features.parquet 51317
1 Attack_long_features.parquet 5594
2 benign_features.parquet 102971396
3 benign_long_features.parquet 445756
4 CnC_features.parquet 49288
5 CnC_long_features.parquet 15738
6 DDoS_features.parquet 53052636
7 DDoS_long_features.parquet 6919
8 Download_features.parquet 8983
9 Download_long_features.parquet 1828
10 Okiru_1_features.parquet 102224916
11 Okiru_1_long_features.parquet 34836
12 PortScan_1_features.parquet 87505926
13 PortScan_1_long_features.parquet 58814

In [3]:
df_list = []

# read files that contains the word 'long'
for file in files:
    if 'long' in file:
        # read the parquet file
        df = pd.read_parquet(dir + file)
        # append the dataframe to the list
        df_list.append(df)

# concatenate the dataframes
long_df = pd.concat(df_list)

In [4]:
# print the unique values in long columns
for column in long_df.columns:
    print(long_df[column].unique())

['SF' 'RSTO' 'S2' 'S0' 'RSTR' 'REJ' 'RSTOS0' 'S1' 'OTH' 'SH' 'RSTRH' 'SHR'
 'S3']
['ShADadFf' 'ShADfrFr' 'ShADadtCFf' 'ShADdaFf' 'ShADadCFf' 'ShADdacFf'
 'ShADdfFa' 'ShAdDaFf' 'ShADadtFf' 'ShADdaCFf' 'ShADfFr' 'ShADadCcFf'
 'ShADFfr' 'ShADadfF' 'DdAaFf' 'ShADadcFf' 'ShADdafF' 'ShADdfFr'
 'ShADadCfF' 'ShADadCtFf' 'ShADdatcFf' 'ShADadftF' 'ShADdaftF'
 'ShADdCacFf' 'ShADdFfa' 'ShADdFfaRR' 'ShADadFfRR' 'ShADfFrr' 'ShADadTFf'
 'ShADdaTFf' 'ShADadFRf' 'ShADadTFTf' 'ShADdFaf' 'ShADafF' 'ShR' '^hR'
 'ShADF' 'ShAdDaTR' 'S' 'ShAdDaTRr' 'Sr' 'ShAr' 'ShAdDafr' 'ShAdDaR'
 'ShAdDafR' 'ShAfFa' 'ShAdr' 'SaR' 'ShAdDaFR' 'ShAfr' 'ShAdFaRf'
 'ShAdDafF' 'ShAfFr' 'ShAdDaTFf' 'ShAF' 'ShAdfFa' 'ShAaww' 'ShwAr' 'ShwA'
 'ShAaw' 'ShAdDaTfr' 'ShAfdtF' 'ShAdDaRr' 'ShAdDaTfRr' 'ShAfF' 'ShAfdtFa'
 'ShAFr' 'ShAdfr' 'ShAdDaRR' 'ShAdfDr' 'ShArr' 'ShAdDR' 'ShAdDatRRR'
 'ShAdDatR' 'ShAdDaTRft' 'ShAdDaTRf' 'ShAdDaTTRf' 'ShAdDaTfR' 'ShAar'
 'ShA' 'ShAFa' 'ShAdFaf' 'ShAdDaFfR' 'ShAdDaFRf' 'ShADFfR' 'ShAdDaFRRfR'
 'ShAdDaFRRRf' 'ShAdDFf' 'ShAdDatFf' 'ShAdDaFTf' 'ShAdDaFRfRR'
 'ShAdDaFRfR' 'ShADFfa' 'ShAdDaFfr' 'ShAafF' 'ShAdDFaf' 'ShAdDaFfRR'
 'ShAdDtaFf' 'ShAdDaFRRf' 'ShAadDFf' 'ShAadDFRf' 'ShAdDaTFRf' 'SahAdDFRf'
 'SahAdDFf' 'DFafA' 'SahAdDtFf' 'ShADFadfR' 'Dd' 'D' '-' '^c' 'DAd' 'SAD'
 'ShADa' 'DdA' 'ShADFr' 'ShADaFr' 'ShADr' 'ShAdDfFa' 'ShADar' 'HaDdAFf'
 'Fa' 'ShAdDaftF' 'R' '^r' 'ShADdFf' 'ShADdtaFf' 'ShADaF' 'ShADadtRf'
 'ShADadftFR' 'ShAdDtaR' 'ShAdDtafF' 'FfA' 'F' 'ShADrfR' 'ShAdDar' '^d'
 'D^' 'Fr' 'HaDdR' 'ShrA' 'HaDdAfF' 'HaFfA' 'Ar' 'FaAr' 'HaDdAFTf' 'HaR'
 'FaR' 'Ffa' 'HaADdFf' 'HaDdTAFf' 'HafFr' 'ShAFf' 'ShADadtfF' 'ShAFaf'
 'ShADafdtF' 'ShADacfgF' 'ShADacgdFf' 'ShADCaGdfF' 'ShADCaGdFf' 'ShADadfr'
 'AaDd' 'ShADadRRR' 'ShADadr' 'ShADadf' 'DRr' 'ShADad' 'ShADadttWWtf'
 'ShADadfFr' 'ShADadtf' 'DadA' 'ShADadfRr' 'ShADadRf' 'ShADadtfRr'
 'ShAFfa' 'ShADadtftr' 'ShAaDdFf' 'DdAtfFa' 'ShADadtFRfR' 'ShADadft' '^f'
 'ShDadAttt' 'ShADacdftF' 'ShADacdtttfF' 'ShADacdtfF' 'ShADacfF'
 'ShADadtfFr' 'ShADadtctfF' 'ShADadtTfFr' 'ShADadttFf' 'ShADadFRfR'
 'ShADacdFf' 'ShADadttFRfR' 'ShADfr' 'ShADfrr' 'ShwR' 'ShADadF' '^fA'
 'ShADadFRR' 'ShADacdtfr' 'ShAdaw' 'ShADdaFr' 'DdAFaf' 'Hr' 'ShADFafdtRR'
 'ShADFadfRR' 'D^d' 'HWr' '^hRr' 'HrR' '^hwR' '^hRRRRRaR' '^hRaRr'
 'ShAFfar' 'ShADFaf' 'DdAa' 'ShADFadRf' 'ShADFadftR' 'ShADFrRfaR'
 'ShADFaTdfR' 'ShADFaTfdtR' 'ShADFa' 'ShADFrfR' 'ShADFafR' 'Aa' 'DaFfA'
 'ShADFar' 'ShADFadtRf' 'ShADFafdtR' 'ShADFdfR' 'ShAD' 'ShADFdafRR'
 'ShADFaTf' 'ShAFar' 'ShADFaTr' 'ShADFaT' 'ShADFdRafR' 'ShADFaTdRf'
 'ShADFdRf' 'ShADFadRtf' 'ShADFfaRR' 'ShADFfRaR' 'ShADFafRdt' 'ShADFarR'
 'ShADFaTdftR' 'ShADFadR' 'ShADFadRftr' 'ShADFadRfR' 'ShwAaFdfR'
 'ShADFfdtaRR' 'ShADFdfaRR' 'HadfDrArR' 'ShAFafr' 'ShADFadfRt' '^ha' 'H'
 'ShADadttcfF' 'ShADadtcfF' 'DdAtaFf' 'ShADadtctfFR' 'ShADadttfF' 'Dr'
 'ShADadfR' 'ShAdfDF' 'ShAdDaTfF' 'ShAdDaTFR' '^dtt' 'DrF' 'DFr' 'ShAdfF'
 'ShAdtfFa' 'ShAdaDR' 'ShAdDaFRR' 'ShAdDaRRR' 'HaDdAr' 'ShAadDr'
 'ShAdDaFr' '^aA' 'ShADFaR' 'ShArR' 'ShAdDaF' 'ShAa' 'ShAdDaFT' 'ShADaR'
 'ShAadDFR' 'SahAdDF' 'ShAdDaFrR' 'ShAdDaFRr' '^dDA' 'ShAdDaf' 'ShAdDaft'
 'ShADdaf' 'ShAfdtDr' 'ShAdDaT' 'ShwAadDfr' 'ShwAadDfF' 'ShADdfr'
 'ShAfdtDFr' 'ShADdTafF' '^hwAadDfF' 'ShwAadDftF' 'ShADadfFR' 'DdAf'
 'ShAdDatf' 'ShAdDatfr' 'ShDadAf' 'ShAdD' 'ShAdDfr' 'ShAdDa' 'ShADaTdR'
 'ShADadtR' 'ShADfF' 'ShADadR' 'ShADafFr' 'ShADdR' 'ShADaTdtR' 'ShADaTfF'
 'ShADda' 'ShADdfrFr' 'ShADdar' 'ShADdrfFr' 'ShAdfR' 'ShADfdtrFr'
 'ShADard' 'ShADdfFrr' 'ShAfdtR' 'ShADfdtFr' 'ShADadcgttfF' 'ShADadcgtftF'
 'ShADadfrr' 'ShADadFfR' 'ShADaCGdtfF' 'ShADaCGr' 'ShADCaGcgd'
 'ShADaCGcgdF' 'ShADaCGdt' 'C' 'CCCC' 'CCC' 'I' 'DTT' 'DT' 'SI' 'ShADdfF'
 'ShADdattFfR' 'ShADdf' 'ShADdtatFfR' 'DdAttfrF' 'ShADadtftF' 'ShAdaFr'
 'ShADafr' 'ShADarfF' 'ShAdDaTF' 'ShAdtDaFrR' 'ShAdDatFr' 'ShAdtDaFr'
 'ShAdDatFrR' 'ShAdDatfF' 'ShAdDfFr' 'ShAdDafFr' 'ShADdafR' 'ShAdF'
 'ShAdDafrR' 'ShAdDafFrR' 'ShADfdtR' 'ShAdDarfR' 'SahAdDrfR' 'ShAdDatrfR'
 'ShAdDr' 'ShAdDTafF' 'ShAdDaTFfR' 'ShAFfR' 'ShAdDafrFr' 'ShAdDtaFr'
 'ShAdDFar' 'ShAdDarr' 'ShAdDafFR' 'ShADdfR' 'ShAFafR' 'ShAdDaftFR'
 'ShADfaF' '^hADafF' 'ShADfFa' 'ShAdDFfR' 'ShAdfDFr' '^aR' 'ShAadDfF'
 'ShADfdtFaR' 'ShAFdRfR' 'ShAdDafFrr' 'ShAdtDafF' 'ShAdDtafFr' 'ShADfR'
 '^hADadfR' '^hA' 'ShAFdfRt' '^hADFr' 'ShADfrF' '^hADr']

In [5]:
# if the value contains string 'RST' in column conn_state, replace it with 'RST'
long_df.loc[long_df['conn_state'].str.contains('RST'), 'conn_state'] = 'RST'

# if the value contains string 'SH' in column conn_state, replace it with 'SH'
long_df.loc[long_df['conn_state'].str.contains('SH'), 'conn_state'] = 'SH'

# if the value is 'SF' in column conn_state, replace it with 'S0
long_df.loc[long_df['conn_state'] == 'SF', 'conn_state'] = 'S0'

In [6]:
# if the value is 'S1', 'S2', 'S3' in column conn_state, replace it with 'S'
long_df.loc[long_df['conn_state'].isin(['S1', 'S2', 'S3']), 'conn_state'] = 'S'

print(long_df['conn_state'].value_counts())

S0     96455026
OTH     3715153
RST     2133025
REJ       40330
S          2960
SH          440
Name: conn_state, dtype: int64

In [7]:
print(long_df['history'].value_counts())

S              95797478
C               3592643
I               2119476
D                605266
DTT               65534
                 ...
ShADFarR              1
ShADFaTdftR           1
ShADFadRftr           1
ShwAaFdfR             1
^hADr                 1
Name: history, Length: 399, dtype: int64

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TfidfVectorizer with n-gram range
vectorizer = TfidfVectorizer(analyzer='char', lowercase=False)

# Fit and transform the history column
tfidf_matrix = vectorizer.fit_transform(long_df['history'])

# Convert the matrix to a DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

In [9]:
tfidf_df.head()

,-,A,C,D,F,G,H,I,R,S,...,^,a,c,d,f,g,h,r,t,w
0,0.0,0.398085,0.0,0.251644,0.407033,0.0,0.0,0.0,0.0,0.045091,...,0.0,0.404385,0.0,0.361076,0.402585,0.0,0.393086,0.0,0.0,0.0
1,0.0,0.398085,0.0,0.251644,0.407033,0.0,0.0,0.0,0.0,0.045091,...,0.0,0.404385,0.0,0.361076,0.402585,0.0,0.393086,0.0,0.0,0.0
2,0.0,0.398085,0.0,0.251644,0.407033,0.0,0.0,0.0,0.0,0.045091,...,0.0,0.404385,0.0,0.361076,0.402585,0.0,0.393086,0.0,0.0,0.0
3,0.0,0.398085,0.0,0.251644,0.407033,0.0,0.0,0.0,0.0,0.045091,...,0.0,0.404385,0.0,0.361076,0.402585,0.0,0.393086,0.0,0.0,0.0
4,0.0,0.398085,0.0,0.251644,0.407033,0.0,0.0,0.0,0.0,0.045091,...,0.0,0.404385,0.0,0.361076,0.402585,0.0,0.393086,0.0,0.0,0.0

In [10]:
# drop the history column 
long_df = long_df.drop('history', axis=1)

long_df.head()

  conn_state
0         S0
1         S0
2         S0
3         S0
4         S0

In [11]:
print(long_df.shape)
print(tfidf_df.shape)

(102346934, 1)
(102346934, 22)

In [12]:
# concatenate the dataframes
df_tf = pd.concat([tfidf_df, long_df], ignore_index=True, axis=1)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [ ]:
# read all the csv files in the directory
for file in files:
    # if file name does not contain the word 'long'
    if 'long' not in file:
        # read the parquet file
        df = pd.read_parquet(dir + file)
        # append the dataframe to the list
        df_list.append(df)

df_ip = pd.concat(df_list, axis=0)

print(df_ip.shape)

In [ ]:
df = pd.concat([df_tf, df_ip], ignore_index=True, axis=1)

df.shape

In [32]:
out_dir = parent_dir + '/transformed/'

# write the dataframe to parquet file
df.to_parquet(out_dir + 'transformed.parquet', index=False)