In [2]:
import os
import pandas as pd

dir = os.path.realpath('..').replace('\\', '/')

file_dir = dir + '/data/'

df = pd.read_csv(file_dir + 'df.csv')
df_class = pd.read_csv(file_dir + 'df_class.csv')

C:\Users\Stone\AppData\Local\Temp\ipykernel_18988\917795199.py:8: DtypeWarning: Columns (0,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_dir + 'df.csv')

In [3]:
df_target = df_class[['target']]

In [4]:
malious_index = df_target[df_target['target'] == 'Malicious'].index

# df_benign is the rows with the same index as the 'Benign' class in df
df_malicious = df.loc[malious_index]

df_malicious.shape

(135708501, 21)

In [5]:
# add a target column to df_malicious with the value 1
df_malicious['target'] = 1

df_malicious.head()

,time,string,addr,port,addr.1,port.1,enum,string.1,interval,count,...,bool,bool.1,count.2,string.3,count.3,count.4,count.5,count.6,tunnel_parents,target
0,1525879831.015811,CUmrqr4svHuSXJy5z7,192.168.100.103,51524.0,65.127.233.163,23.0,tcp,-,2.999051,0,...,-,-,0.0,S,3.0,180.0,0.0,0.0,(empty),1
1,1525879831.025055,CH98aB3s1kJeq6SFOc,192.168.100.103,56305.0,63.150.16.171,23.0,tcp,-,-,-,...,-,-,0.0,S,1.0,60.0,0.0,0.0,(empty),1
2,1525879831.045045,C3GBTkINvXNjVGtN5,192.168.100.103,41101.0,111.40.23.49,23.0,tcp,-,-,-,...,-,-,0.0,S,1.0,60.0,0.0,0.0,(empty),1
3,1525879832.01624,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,-,2.998796,0,...,-,-,0.0,S,3.0,180.0,0.0,0.0,(empty),1
4,1525879832.024985,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,-,-,-,...,-,-,0.0,S,1.0,60.0,0.0,0.0,(empty),1

In [6]:
# save df_malicious to csv
df_malicious.to_csv(file_dir + 'df_malicious.csv', index=False)